os:
    - ios
language: generic
osx_image: xcode10
sudo: required
dist: trusty
env:
    - SWIFT_VERSION=4.0
    - SWIFT_VERSION=4.1
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
    - swift test
